### ISSUE TITLE
Session 4: check overview slide

### ISSUE THREAD

**Issue by csch0lz** [csch0lz/UsingRTutorials2425#7]
Check slide "Overview tidying steps"

**Comment by xgaouva** [comment]
## Overview Data Tidying Steps

-   Determine the initial structure of your dataset. _(what does this mean?)_
-   What are they primary keys? _(Maybe remove this as it makes more sense to check primary keys after checking P1, P2 P3?)_
-   What violations of the tidy data principles can you see?
-   Address any issues:
    -   Start with Principle 1 (redistributing data to different tibbles
        if necessary) _(Should first check duplicated rows even before P1)_
    -   Continue with Principle 2 (pivot_longer)  
    -   Finish by addressing issues for Principle 3 and 4
-   Confirm and document the new structure of your dataset.
    -   What are the primary and foreign keys of the final data set? _(Should this even be the last step after join?)_
    -   How can different data sources be joined? 

This concludes data tidying.

**Comment by csch0lz** [comment]
Thanks @xgaouva ! I made some adjustments. Couple of responses to your comments:
1. They should check primary keys before doing anything to the dataset. That is part of determining what the structure of their dataset is. If they don't understand exactly what is in their data and how its structure, they can't tidy it effectively. 
2. Checking for duplicate rows is part of checking for a primary key (i.e. there is not primary key if there are duplicates). 
3. Joining is not part of data tidying. Data tidying ends with separate dibbles for different types of data. At the end of tidying, they should be able to describe how different data sources CAN be joined, but the actual joining would be part of a specific analysis, not the data tidying process.
